import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import Card from './Card';
import Loader from './Loader';
import midJourneyImage from '../assets/header.png';
import aboutImage from '../assets/about.png';
import FlagError from './FlagError';
// Selectors
import { useAppSelectors } from '../hooks/useAppSelectors';
// Slices
import { setLoading } from '../slices';
import Footer from './Footer';

export default function AppLayout() {
  const navigate = useNavigate();
  const location = useLocation();
  const dispatch = useDispatch();
  const {
    isLoading: apiLoading,
    apiError,
    loadingReason,
    generatedImage,
  } = useAppSelectors();

  useEffect(() => {
    if (apiError) {
      // Stop showing the loader if there is an error
      dispatch(setLoading([false]));
    }
  }, [apiError]);

  const isLoading = navigate.state === 'loading' || apiLoading;

  let headerImage;
  let alt;
  switch (true) {
    // Show the AI generated pizza image if available
    case location.pathname.includes('/order/') && generatedImage !== '':
      headerImage = generatedImage;
      alt = 'Pizza image generated by Dall-e';
      break;
    case location.pathname.includes('/about'):
      headerImage = aboutImage;
      alt = 'Jawad Shuaib';
      break;
    default:
      headerImage = midJourneyImage;
      alt = 'Header image created using Stable Diffusion';
      break;
  }

  // function handleBannerClick() {
  //   navigate('/');
  // }

  return (
    <div className="grid place-items-center h-screen text-center dark:bg-gray-800">
      <div className="flex flex-col items-center justify-center">
        <Card headerImage={headerImage} alt={alt}>
          <main>
            {apiError && <FlagError />}
            {isLoading ? <Loader reason={loadingReason} /> : <Outlet />}
          </main>
        </Card>
        <Footer />
      </div>
    </div>
  );
}
